# Generated by Django 5.1.1 on 2024-09-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='order_history',
        ),
    ]
