# Generated by Django 5.1.1 on 2024-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
